### ISSUE TITLE
update db form planet file

### ISSUE THREAD

**Issue by normansuesstrunk** [GeoKnow/LinkedGeoData#19]
I deployed the lgd project on a linux machine and imported the swiss planet file. I now wondered if i can update the db without deleting and reimporting the complete planet file? 

many thanks, 
Norman

**Comment by almereyda** [comment]
http://linkedgeodata.org/RDFMapping suggests to use Osmosis for updates.

**Comment by almereyda** [comment]
You could have a look at the 2012 paper at http://linkedgeodata.org/Publications to get an idea of the overall architecture.

**Comment by Aklakan** [comment]
The LGD database uses the OSM simple schema as the base and adds additional tables with mappings and interlinks to it. Hence, its a pure OSM database so that you can use the osmosis tool to apply diffs published by OSM. See the options at http://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.44 - especially --read-replication-interval-init and --write-pgsql-change.
