### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by jindrichmynarz** [GeoKnow/LinkedGeoData#22]
Is the LinkedGeoData project actively maintained? Many links on <http://linkedgeodata.org> are currently dead, including the browser (#18), the [LinkedGeoData Ontology](http://linkedgeodata.org/api/3/ontology), or the Triplify links (such as <http://linkedgeodata.org/resource/triplify/way27743320>).

**Comment by Aklakan** [comment]
Hi jindrich, yes I am still maintaining it; although time is always short :)

According to OSM, [way27743320 was deleted](https://www.openstreetmap.org/way/27743320).
For example, this one works: http://linkedgeodata.org/triplify/way5013364 (note that there is no /resource/)

As for http://linkedgeodata.org/ontology this is indeed an issue, because actually the server is running, but it doesn't give a response. I need to investigate.

As for the browser: for quite a while I want to replace it with [Facete](http://cstadler.aksw.org/facete2/), but unfortunately the app as a whole does not scale to LGD's size at present. In the apps architecture the use of external indices is forseen, but so far I didn't get around to implement them.

Yet, the SPARQL based map component should be capable of it - this is a old demo of it that does live  queries against DBpedia: http://cstadler.aksw.org/jassa-ui/jassa-map-ol-demo

**Comment by jindrichmynarz** [comment]
Thanks for clarifying! Regarding the SPARQL access, do I understand correctly that the Virtuoso-based endpoint at <http://linkedgeodata.org/sparql> is not up-to-date, while the Sparqlify one at <http://linkedgeodata.org/vsparql> is?

**Comment by Aklakan** [comment]
Hi, yes, the vsparql one is live sync'd: [SPARQL query for latest changes](http://linkedgeodata.org/vsnorql/?query=SELECT+*+WHERE+{%0D%0A++%3Fs+dcterms%3Amodified+%3Fo%0D%0A}%0D%0AORDER+BY+DESC%28%3Fo%29)

It still has to catch up a bit (it was down during the download release creation), but this will happen in the coming days.

**Comment by jindrichmynarz** [comment]
Great, thanks for clarification.

**Comment by talespaiva** [comment]
Hi @Aklakan 

is there any plans of updating the Virtuoso-based endpoint? The part that I'm woking with (Grenoble, France) is missing important updates.

While I can get the information I need from the vsparql endpoint, I have experienced that the Virtuoso one (/sparql) is better to query programatically (I'm using the SPARQLWrapper Python package). Despite I can send HTTP posts to /vsparql, the response is error 500 most of time and, when it works, the results are always XML regardless of the output parameter.

Thanks for the great work!
